[package]
name = "alya-chan"
version = "0.1.0"
authors = ["Kiyomi Fujiwara <kiyomi@mjba.my>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-model = "0.17.1"
twilight-cache-inmemory = "0.17.1"
twilight-util = { version = "0.17.0", features = ["builder"] }
twilight-standby = "0.17.0"
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.7"
tracing = "0.1"
url = "2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15"
chrono = "0.4"
twilight-validate = "0.17.0"
rustls = "0.23.35"
sea-orm = { version = "1.1.19", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration = "1.1.19"
libsql = "0.9.29"
uuid = { version = "1", features = ["v4", "serde"] }
once_cell = "1.19"
