services:
  alya-chan:
    image: ghcr.io/idmja/alya-chan:latest
    container_name: alya-chan
    env_file:
      - .env
    ports:
      - "3000:3000"  # TopGG Webhook Server
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./emoji.toml:/app/emoji.toml:ro
      - ./src/models:/app/src/models:ro
      - ./data:/app/data
    restart: unless-stopped
